# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2018.

sudo: false
language: generic
os: linux
stages:
  - name: build
  - name: website update
jobs:
  include:
    - stage: 
      script:
        - export PYTHONPATH=${PWD}/src
        - ./src/script/ci_build.py ++bin-dir=${HOME}/devcache/boost_lib_stats
    - stage: website update
      script:
        - echo "Nothing"
