# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2018.

sudo: false
language: generic
os: linux
dist: xenial
branches:
  only:
    - master
stages:
  - name: build data
  - name: website update
jobs:
  include:
    - stage: build data
      script:
        - export PYTHONPATH=${PWD}/src
        - ./src/script/ci_build.py ++bin-dir=${HOME}/devcache/boost_lib_stats ++build-data
    - stage: website update
      script:
        - rvm --default use 2.3
        - ruby -v
        - gem install asciidoctor
        - asciidoctor --version
        - export PYTHONPATH=${PWD}/src
        - ./src/script/ci_build.py ++bin-dir=${HOME}/devcache/boost_lib_stats ++website-update
        - git config user.email "bls-bot"
        - git config user.name "bls-bot"
        - git commit --all -m "Automatic update. [skip ci]"
        - git push "https://grafikrobot:${GH_TOKEN}@github.com/grafikrobot/boost_lib_stats.git"
before_cache:
  - export PYTHONPATH=${PWD}/src
  - ./src/script/git_switch.py ++root=${HOME}/devcache/boost_lib_stats/boost_root ++branch=develop
cache:
  directories:
    - $HOME/devcache
