= Boost C++ Libraries Statistics
:copyright: Copyright 2018 Rene Rivera
:author: Rene Rivera
:email: grafikrobot@gmail.com
:revdate: {docdatetime}
:reproducible:
:nofooter:
:sectanchors:
:sectnums:
:sectnumlevels: 5
:source-language: c++
:toc: left
:toclevels: 2
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠
:CPP: C++
:PP: ++
:P: +

ifdef::backend-html5[]
++++
<script src="echarts.min.js"></script>
++++
endif::[]

== Introduction

This document represents a collection of possibly relevant and interesting
graphs and statistics about the Boost C++ Libraries collection. The goal is
to shed light on the past and current state of the libraries with the hope
of spurring improvements in the improvement of the collection as a whole.
And to try and do that with some interesting and fun visualizations.

The data is frequently update, usually daily, to reflect current state of
development along side the historical development. Most of the data only
goes back to release 1.57.0 (November 3rd, 2014) as the introspection tools
only deal with the modular arrangement of the libraries.

== Dependency Cycles, Headers

This shows both
the total number of cycles in the Boost libraries ("Cycles")
and
the total number of libraries that are involved in cycles ("Libs In Cycles")
for the library headers of each release.

++++
<div id="cycles_chart_headers" style="height: 660px;"></div>
<script type="text/javascript">
var cycles_chart = echarts.init(document.getElementById('cycles_chart_headers'), null, {renderer: 'svg'});
cycles_chart.setOption({
    grid: [
        { left: '0%', right: '70%', top: '5%', bottom: '0%', containLabel: true },
        { left: '30%', right: '1%', top: '5%', bottom: '0%', containLabel: true }
    ],
    xAxis: [
        { gridIndex: 0, position: 'top', nameLocation: 'center', nameGap: '25', name: 'Cycles', inverse: true },
        { gridIndex: 1, position: 'top', nameLocation: 'center', nameGap: '25', name: 'Libs In Cycles' },
    ],
    yAxis: [
        { type: 'category', gridIndex: 0, axisTick: { show: false } },
        { type: 'category', gridIndex: 1, show: false, axisLabel: { show: false } },
    ],
    series: [
        {
            type: 'bar',
            label: { normal: { show: false, position: 'inside' } },
            encode: { x: 'cycles', y: 'version' },
            xAxisIndex: 0, yAxisIndex: 0
        },
        {
            type: 'bar',
            label: { normal: { show: true, position: 'inside' } },
            encode: { x: 'libs_in_cycles', y: 'version' },
            xAxisIndex: 1, yAxisIndex: 1
        },
    ],
    dataset: { source:
include::cycles_chart_headers.json[]
    }
});
</script>
++++

== Dependency Cycles, Build

This shows both
the total number of cycles in the Boost libraries ("Cycles")
and
the total number of libraries that are involved in cycles ("Libs In Cycles")
for building the libraries of each release.

++++
<div id="cycles_chart_build" style="height: 660px;"></div>
<script type="text/javascript">
var cycles_chart = echarts.init(document.getElementById('cycles_chart_build'), null, {renderer: 'svg'});
cycles_chart.setOption({
    grid: [
        { left: '0%', right: '70%', top: '5%', bottom: '0%', containLabel: true },
        { left: '30%', right: '1%', top: '5%', bottom: '0%', containLabel: true }
    ],
    xAxis: [
        { gridIndex: 0, position: 'top', nameLocation: 'center', nameGap: '25', name: 'Cycles', inverse: true },
        { gridIndex: 1, position: 'top', nameLocation: 'center', nameGap: '25', name: 'Libs In Cycles' },
    ],
    yAxis: [
        { type: 'category', gridIndex: 0, axisTick: { show: false } },
        { type: 'category', gridIndex: 1, show: false, axisLabel: { show: false } },
    ],
    series: [
        {
            type: 'bar',
            label: { normal: { show: false, position: 'inside' } },
            encode: { x: 'cycles', y: 'version' },
            xAxisIndex: 0, yAxisIndex: 0
        },
        {
            type: 'bar',
            label: { normal: { show: true, position: 'inside' } },
            encode: { x: 'libs_in_cycles', y: 'version' },
            xAxisIndex: 1, yAxisIndex: 1
        },
    ],
    dataset: { source:
include::cycles_chart_build.json[]
    }
});
</script>
++++

// == Dependency Levels, Headers

// ++++
// <div id="levels_headers" style="height: 500px;"></div>
// <script type="text/javascript">
// var levels_headers = echarts.init(document.getElementById('levels_headers'));
// levels_headers.setOption({
//     /*
//     series: {
//         type: 'sankey',
//         layout:'none',
//         focusNodeAdjacency: 'allEdges',
//         data: [
//             { name: 'config (1.68.0)'},
//             { name: 'predef (1.68.0)'},
//             { name: 'system (1.68.0)'},
//             { name: '0 (1.68.0)'},
//             { name: '1 (1.68.0)'},
//             { name: '2 (1.68.0)'},
//             { name: 'config (1.69.0)'},
//             { name: 'predef (1.69.0)'},
//             { name: 'system (1.69.0)'},
//             { name: '0 (1.69.0)'},
//             { name: '1 (1.69.0)'},
//             { name: '2 (1.69.0)'},
//         ],
//         links: [
//             { source: 'config (1.68.0)', target: '0 (1.68.0)', value: '1' },
//             { source: 'predef (1.68.0)', target: '1 (1.68.0)', value: '1' },
//             { source: 'system (1.68.0)', target: '2 (1.68.0)', value: '1' },
//             { source: '0 (1.68.0)', target: 'config (1.69.0)', value: '1' },
//             { source: '1 (1.68.0)', target: 'predef (1.69.0)', value: '1' },
//             { source: '2 (1.68.0)', target: 'system (1.69.0)', value: '1' },
//             { source: 'config (1.69.0)', target: '0 (1.69.0)', value: '1' },
//             { source: 'predef (1.69.0)', target: '0 (1.69.0)', value: '1' },
//             { source: 'system (1.69.0)', target: '1 (1.69.0)', value: '1' },
//         ]
//     }
//     */
//     series: [{
//         type: 'custom',
//         renderItem: function (params, api) {
//             var categoryIndex = api.value(0);
//             var startPoint = api.coord([api.value(1), categoryIndex]);
//             var endPoint = api.coord([api.value(2), categoryIndex]);
//             var height = api.size([0, 1])[1] * 0.6;
//             var rectShape = echarts.graphic.clipRectByRect({
//                 x: startPoint[0],
//                 y: startPoint[1] - height / 2,
//                 width: endPoint[0] - startPoint[0],
//                 height: height
//             }, {
//                 x: params.coordSys.x,
//                 y: params.coordSys.y,
//                 width: params.coordSys.width,
//                 height: params.coordSys.height
//             })

//             // Returns definitions for the current `dataItem`.
//             return rectShape && {
//                 type: 'rect',
//                 shape: rectShape,
//                 style: api.style()
//             };
//         },
//         data: [
//             [12, 44, 55, 60], // The first dataItem.
//             [53, 31, 21, 56], // The second dataItem.
//             [71, 33, 10, 20], // The third dataItem.
//         ]
//     }]
// });
// </script>
// ++++

// == Dependency Levels, Build

== Popularity

It's interesting to look at how "popular" a library is relative to other libraries.
It's a reasonable way to discern what to put resources on. And possibly to find
kinds of libraries that users might want. This chart shows the relative popularity
of Boost libraries and tools. The popularity index is computed to account the
GitHub "watchers", "forks", and "stars" weighing their relevance in that order.
The statistics for this graph are current as of the date in this document (above).

++++
<div id="popularity_chart" style="height: 800px; margin-bottom: 1em;"></div>
<script type="text/javascript">
var popularity_chart = echarts.init(document.getElementById('popularity_chart'));
popularity_chart.setOption({
    title: {
        text: 'Popularity',
        subtext: 'GitHub stars, forks, and watchers proportional index.',
        left: 'center'
    },
    tooltip: {
        formatter: function (info) {
            return [
                '<div style="font-weight: bolder; border-bottom: 1px dotted white;">' +
                    echarts.format.encodeHTML(info.name) + '</div>',
                'Forks: ' + echarts.format.addCommas(info.value[1]) + '<br>',
                'Stars: ' + echarts.format.addCommas(info.value[2]) + '<br>',
                'Watchers: ' + echarts.format.addCommas(info.value[3]) + '<br>'
                ].join('');
        }
    },
    series: [
        {
            name: 'Popularity',
            type: 'treemap',
            label: {
                show: true,
                formatter: '{b}'
            },
            levels: [
                {
                    // Root
                    itemStyle: { normal: { gapWidth: 2 } },
                    color: [ '#6a6' ],
                },
                {
                    // Libraries and Tools nodes.
                    upperLabel: { normal: { show: true, height: 40, fontWeight: 'bolder' } },
                    itemStyle: {
                        normal: { borderColor: '#555', borderWidth: 5, gapWidth: 2 },
                        emphasis: { borderColor: '#777' }
                    },
                    visualDimension: 2,
                    colorSaturation: [0.2, 0.6],
                },
                {
                    // Individual lib/tools nodes.
                }
            ],
            data:
include::popstats.json[]
        }
    ]
});
</script>
++++

****
Use the mouse/touch to move the graph. And use the scroll wheel / pinch to zoom.
****


== Acknowledgments

This document would not be possible without the fantastic work by Peter Dimov
in creating the `boostdep` tool.
