# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt)
#
# Copyright René Ferdinand Rivera Morell 2021.

name: Boost Stats

on:
  push:
    branches: ["master"]

jobs:
  build_data:
    name: Build Data
    runs-on: ubuntu-latest
    steps:
      - { name: "Checkout", uses: actions/checkout@v2 }
      - name: Set up Python
        uses: actions/setup-python@v2
        with: { python-version: "3.x" }
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with: { ruby-version: 2.x }
      - name: "Cache"
        uses: actions/cache@v2
        with:
          path: ~/devcache
          key: ${{ runner.os }}-build
      - name: "Build Data"
        run: |
          export PYTHONPATH=${PWD}/src
          ./src/script/ci_build.py ++bin-dir=${HOME}/devcache/boost_lib_stats ++build-data
      - name: "Cleanup"
        run: |
          export PYTHONPATH=${PWD}/src
          ./src/script/git_switch.py ++root=${HOME}/devcache/boost_lib_stats/boost_root ++branch=develop
      - name: "Website Update"
        run: |
          set -e
          uname -a
          ruby -v
          gem install asciidoctor
          asciidoctor --version
          export PYTHONPATH=${PWD}/src
          ./src/script/ci_build.py ++bin-dir=${HOME}/devcache/boost_lib_stats ++website-update
          git config user.email "bls-bot"
          git config user.name "bls-bot"
          git commit --all -m "Automatic update. [skip ci]"
          git push "https://grafikrobot:${GH_TOKEN}@github.com/grafikrobot/boost_lib_stats.git" HEAD:master
